### ISSUE TITLE
자기소개서 페이지 구현

### ISSUE THREAD

**Issue by constantly-dev** [mju-likelion/eclair#7]
## 💡Description
메인 페이지에서 링크 선택 시 연결되는 자기소개서 페이지 구현

## ✅ Tasks
- [ ] 자기소개서 페이지 UI
- [ ] 메인 페이지 링크 선택 시 해당 자기소개서 페이지 연결
- [ ] 주소 내 학번으로 자기소개서 GET API
